BASECAMP_USERNAME: basecamp_username
BASECAMP_PASSWORD: basecamp_password
BASECAMP_ID: 999999 # http://basecamp.com/<BASECAMP_ID>
SLACK_INSTANCE: slack_instance_name # http://<SLACK_INSTANCE>.slack.com
SLACK_WEBHOOK_URL: slack_webhook_url # https://hooks.slack.com/services/<webhook_url>
SLACK_BOT_NAME: basecamp
SLACK_BOT_ICON: # full URL to bot icon
SLACK_DEFAULT_CHANNEL: "#basecamp" # the default channel that messages will be posted to
SLACK_CHANNELS:
  Basecamp Project Name: "#slack_channel_name"
